Lotte-Feelmycode/the-parabole-mono-be

- src/main/java/com/feelmycode/parabole/controller/ProductController.java
> [feature/product] !Hotfix!

- build.gradle
- src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
- src/main/java/com/feelmycode/parabole/domain/EventParticipant.java
- src/main/java/com/feelmycode/parabole/dto/EventApplyDto.java
- src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
- src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
전 pr 코드 스타일 변경
코드 스타일 수정
전체적인 코드 띄어쓰기들 다 변경했어요
날짜 값 6자리로 똑바로 들어가는지만 확인하면 될 것 같아요
예와처리들 설정
#16
> [feature/eventapply] 이벤트 응모 API 수정, 코드 스타일 변경 [#16]

- src/main/java/com/feelmycode/parabole/controller/ProductController.java
- src/main/java/com/feelmycode/parabole/global/error/TestError.java
- src/main/java/com/feelmycode/parabole/global/error/exception/ExampleException.java
- src/main/java/com/feelmycode/parabole/global/error/exception/NoDataException.java
- src/main/java/com/feelmycode/parabole/service/ProductService.java
Product에 Response Entity 및 Custom Error 적용
- Product에 Response Entity 및 Custom Error 적용
- Error custom 예시 추가
적용 방법봐주세요!
API 문서도 꼭! 수정해주세요
[#31][#48]
> [Feature/productList] Product에 Response Entity 및 Custom Error 적용

- build.gradle
- src/docs/asciidoc/example.adoc
- src/main/java/com/feelmycode/parabole/controller/ProductController.java
- src/main/resources/log4j2.xml
- src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
프로젝트에  추가적으로 Spring Rest Docs와 Logging 설정
Spring Rest Docs설정과 Logging(Slf4j, Log4j2) 추가 및 테스트 코드
[Spring Rest Docs & Logging](https://jungew1509.notion.site/Spring-Rest-Docs-Logging-c8613afb16554b9887d0dfc3b70fec63)
Spring Rest Docs를 자동으로 Swagger 문서로 만드는 것
[#44] [#62]
> [feature/setting] Spring Rest Docs, Logging설정 추가 및 테스트

- src/main/java/com/feelmycode/parabole/controller/CouponController.java
- src/main/java/com/feelmycode/parabole/dto/CouponUseAndAssignRequestDto.java
- src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
- src/main/java/com/feelmycode/parabole/repository/UserCouponRepository.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
Coupon에 Response Entity 및 Custom Error 적용 Fix
우리 팀 약속된 ParaboleResponse 와 ParaboleException 을 적용
HTTP Error 메시지를 처음 사용해 봤어요,
각 상황별로 적합한 에러코드를 작성했는지 봐주세요 :)
(예시 : [#23 ])
> [feat/coupon] Coupon에 Response Entity 및 Custom Error 적용

- src/main/java/com/feelmycode/parabole/controller/UserController.java
- src/main/java/com/feelmycode/parabole/domain/User.java
- src/main/java/com/feelmycode/parabole/dto/UserSigninDto.java
- src/main/java/com/feelmycode/parabole/dto/UserSignupDto.java
- src/main/java/com/feelmycode/parabole/repository/UserRepository.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
User API
User 회원가입, 로그인 API 작성, 각 상황에 맞는 Response Error 메시지 작성
저는 200, 201, 400 만 쓰고 있는데 상황별로 HTTP STATUS 가 적절히 사용되었는지 ,
혹시 다른 에러 코드를 사용하는게 더 나은지 한번 봐주세요 !
feature/user 브랜치 너무 많이 지웠다 팠다 죄송,, 
제 dirty code 를 하나하나 봐주시는 언니 오빠들이 고생이 너무 많아서 항상 미안해요 😢
마이페이지 내 정보 Read API 추가 예정
User 안에 Seller 를 가지고 있어서 JPA 연관관계 처리해줄 예정
Order 생성시 User(주인) 에서 호출하는 User-Order 연관관계 메서드 작성 예정
User(주인)-Cart 관계 생성
User-EventParticipant 관계 생성
User-EventWinner 연관관계 메서드 생성
Testing 의 어려움 때문에 JWT 추가는 나중에 하기로 팀원들과 이야기 되었습니다.
[#51] [#53]
> WIP [feature/user] User 회원가입, 로그인 API

- src/main/java/com/feelmycode/parabole/controller/CartController.java
- src/main/java/com/feelmycode/parabole/domain/Cart.java
- src/main/java/com/feelmycode/parabole/domain/CartItem.java
- src/main/java/com/feelmycode/parabole/dto/CartItemDto.java
- src/main/java/com/feelmycode/parabole/dto/CartItemRequestDto.java
- src/main/java/com/feelmycode/parabole/repository/CartItemRepository.java
- src/main/java/com/feelmycode/parabole/repository/CartRepository.java
- src/main/java/com/feelmycode/parabole/service/CartItemService.java
- src/main/java/com/feelmycode/parabole/service/CartService.java
Cart CRUD 및 Cart 예외처리 추가를 위해
Cart CURD 생성, Cart 예외처리 추가
제가 중간에 commit하다가 로컬에서 충돌이 일어나서 최종 커밋 부분만 보시면 됩니다.
카트에 CRUD가 정확하게 되는지 예외처리가 추가되는지 확인하시면 될 것 같습니다.
test code 작성
#28
> [feature/cart] Cart CRUD , ResponseEntity 및 Custom Error 적용

- src/main/java/com/feelmycode/parabole/controller/UserController.java
- src/main/java/com/feelmycode/parabole/domain/User.java
- src/main/java/com/feelmycode/parabole/dto/UserInfoResponseDto.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
Feat: User 마이페이지에서 개인정보 반환
User 정보 반환 API
~~User 가 String imgUrl 을 가지고 있어요
회원가입시에 프로필 사진을 파일 업로드 통해서 올리는지 궁금합니다~~
Erd 도 수정해주었습니다.
[#70]
> [feature/user] User 마이페이지에서 개인정보 반환

- src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
- src/main/java/com/feelmycode/parabole/domain/EventParticipant.java
- src/main/java/com/feelmycode/parabole/dto/EventApplyDto.java
- src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
- src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
이벤트 응모 ResponseEntity 및 예외처리 추가
예외처리 수정
예외처리 다 추가햇고요
예외처리할 때 다 찾을 수 없는거라 notfound로 햇는데 혹시나 아닌거같으면 말해줘용
테스트 코드 작성 및 API 문서 수정
#72
> [Feature/eventapply] 이벤트 응모 ResponseEntity 및 예외처리 추가

- src/main/java/com/feelmycode/parabole/controller/ProductController.java
- src/main/java/com/feelmycode/parabole/domain/Product.java
- src/main/java/com/feelmycode/parabole/domain/ProductDetailRepository.java
- src/main/java/com/feelmycode/parabole/dto/ProductDetailListResponseDto.java
- src/main/java/com/feelmycode/parabole/service/ProductDetailService.java
- src/main/java/com/feelmycode/parabole/service/ProductService.java
- src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
- src/test/java/com/feelmycode/parabole/service/ProductServiceTest.java
상품과 상품의 이미지를 추가하는 작업을 진행했습니다.
실제 동작할 때 생기는 문제점 위주로 봐주시면 감사하겠습니다.
ProductServiceTest에서 throw Exception이 날라오는 것을 확인했고 postman을 사용해서 값이 잘 보내지고 받아지는지는 확인하지 않았습니다.
부족한 로직을 고민하여 추가할 예정입니다. 
`참견환영`
[#42] [#66] [#47]
> [feature/product] Product와 ProductDetail기능 추가 

- src/main/java/com/feelmycode/parabole/dto/OrderInfoListDto.java
- src/main/java/com/feelmycode/parabole/repository/OrderRepository.java
- src/main/java/com/feelmycode/parabole/service/OrderService.java
OrderInfoListDto 추가
주문에 상품을 추가하는 내용 추가
주문정보에 Coupon추가하기
[#42]
> [feature/order] OrderInfoListDto 추가

- src/main/java/com/feelmycode/parabole/controller/CouponController.java
- src/main/java/com/feelmycode/parabole/domain/Coupon.java
- src/main/java/com/feelmycode/parabole/domain/CouponType.java
- src/main/java/com/feelmycode/parabole/domain/CouponUseState.java
- src/main/java/com/feelmycode/parabole/domain/Seller.java
- src/main/java/com/feelmycode/parabole/domain/User.java
- src/main/java/com/feelmycode/parabole/domain/UserCoupon.java
- src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
- src/main/java/com/feelmycode/parabole/dto/CouponCreateResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/CouponUserResponseDto.java
- src/main/java/com/feelmycode/parabole/enumtype/CouponType.java
- src/main/java/com/feelmycode/parabole/enumtype/CouponUseState.java
- src/main/java/com/feelmycode/parabole/repository/UserCouponRepository.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
- src/test/java/com/feelmycode/parabole/service/UserServiceTest.java
Seller - Coupon - UserCoupon - User Entity 사이에 JPA 적용하여 Table Mapping 작업
이번 PR 의 주된 작업은 각 엔티티 간의 연관 관계 메서드의 위치와 주인을 분별하고 수정하는 작업을 진행하였습니다.
[#76 ]
> [feature/coupon] jpa 적용 작업

- src/main/java/com/feelmycode/parabole/global/config/TestConfig.java
- src/main/java/com/feelmycode/parabole/global/config/WebMvcConfig.java
프론트엔드 작업 시작하면서 필요한 CORS설정을 추가하였습니다
추후 개발서버 배포하게 되면 변경 가능성 있습니다.
CORS설정을 위한 WebConfig 클래스 추가
프론트엔드 배포 서버에 대한 origin 주소 추가
[#83]
> [Feat/CORS] CORS 설정 (개발 서버 배포후 수정예정)

- src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/CouponUserResponseDto.java
- src/main/java/com/feelmycode/parabole/enumtype/CouponUseState.java
EnumType 사용방법 수정
EnumType 을 클린코드하게 사용하기
[https://github.com/Lotte-Feelmycode/the-parabole-mono-be/pull/75](url) 에
@jungeu1509 comment 반영 작업
> [feature/coupon] EnumType 사용방법 수정

- src/main/java/com/feelmycode/parabole/controller/EventController.java
- src/main/java/com/feelmycode/parabole/domain/Event.java
- src/main/java/com/feelmycode/parabole/domain/Seller.java
- src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
- src/main/java/com/feelmycode/parabole/dto/EventDto.java
- src/main/java/com/feelmycode/parabole/dto/EventListResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/EventPrizeCreateRequestDto.java
- src/main/java/com/feelmycode/parabole/service/EventService.java
Seller작업의 완료로 Seller_id를 사용하고 있는 기존 Event 서비스를 수정하였습니다.
이벤트 도메인 관련 내용 수정
Seller 도메인에 이벤트리스트 추가하였습니다 연관관계 및 메소드 적절한지 리뷰부탁해요
@daeunchung 님은 꼭 봐주세요
[#81]
> [Feature/event-seller] Event-Seller 매핑

- src/main/java/com/feelmycode/parabole/controller/CouponController.java
- src/main/java/com/feelmycode/parabole/domain/Coupon.java
- src/main/java/com/feelmycode/parabole/domain/UserCoupon.java
- src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
- src/main/java/com/feelmycode/parabole/dto/CouponCreateResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/CouponInfoResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
- src/main/java/com/feelmycode/parabole/enumtype/CouponType.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
기능 수정
CouponController 에서 sellerId 를 Arg로 받는 API 전부 userId 로 로직 수정
[#89 ]
> [feature/coupon] CouponController 에서 sellerId 를 Arg로 받는 API 전부 userId 로 로직 수정

- src/main/java/com/feelmycode/parabole/controller/UserController.java
- src/main/java/com/feelmycode/parabole/domain/User.java
- src/main/java/com/feelmycode/parabole/global/error/exception/NotSellerException.java
- src/main/java/com/feelmycode/parabole/service/SellerService.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
[feature/user]  User-Seller Role 확인 및 반환 기능 
[#89] 에서 필요한 User-Seller Role 확인 및 반환 기능 추가
안내 말씀 남겨요. #90 과 #92 가 모두 dev 로 머지되어야 수정한 로직이 동작합니다.
마지막 커밋은 2022-09-30 21:30 에 달린 코멘트들까지 반영하여 코드 수정되어 있습니다.
추가로 수정해야 할 부분 있으면 comment 달고 @daeunchung 에게 톡 한번 남겨주세요, 
없으면 approve 부탁해요
[#91 ]
> [feature/user] 계정의 Role 확인 및 반환 

- src/main/java/com/feelmycode/parabole/domain/User.java
- src/main/java/com/feelmycode/parabole/dto/UserSignupDto.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
> [feature/user] User 에 연락처 추가

- src/test/java/com/feelmycode/parabole/service/UserServiceTest.java
(제목은 작업한 내용을 간결하게 작성해주세요)
(작업중일 경우 제목 맨 앞에 [WIP]를 붙여주세요.)
(PR을 시작하게된 이유)
(어떤 부분 중점으로 봐달라, ~ 부분 잘 모르겠다, ~ 테스트 필요함 등)
(테스트 결과 첨부 혹은 리뷰어가 테스트할 수 있는 방법 제시)
(예시 : [#1][#2])
(괄호는 모두 지워주세요)
> fix cicd test

- src/main/java/com/feelmycode/parabole/controller/CartController.java
- src/main/java/com/feelmycode/parabole/controller/OrderController.java
- src/main/java/com/feelmycode/parabole/domain/CartItem.java
- src/main/java/com/feelmycode/parabole/dto/CartAddItemRequestDto.java
- src/main/java/com/feelmycode/parabole/service/CartItemService.java
- src/main/java/com/feelmycode/parabole/service/CartService.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
주문 및 장바구니 기능 수정
- 주문생성을 POST 매핑으로 변경
- CartItem.java 안쓰는 import 삭제
- CartItem 을 새로 추가하는 DTO 생성
- CartItem을 추가하는 알고리즘 변경
- 회원가입시 cart 생성되도록 추가
주문생성 POST 매핑으로 변경
CartItem 추가하는 알고리즘 변경
회원가입시 장바구니 생성되는 알고리즘 추가
> [Feature/productDetailApi] 주문 및 장바구니 기능 수정

- src/main/java/com/feelmycode/parabole/controller/CartController.java
- src/main/java/com/feelmycode/parabole/controller/SellerController.java
- src/main/java/com/feelmycode/parabole/domain/Cart.java
- src/main/java/com/feelmycode/parabole/dto/CartItemDeleteRequestDto.java
- src/main/java/com/feelmycode/parabole/dto/CartItemDto.java
- src/main/java/com/feelmycode/parabole/dto/CartItemGetResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/CartItemUpdateRequestDto.java
- src/main/java/com/feelmycode/parabole/dto/SellerDto.java
- src/main/java/com/feelmycode/parabole/repository/CartItemRepository.java
- src/main/java/com/feelmycode/parabole/repository/CartRepository.java
- src/main/java/com/feelmycode/parabole/repository/SellerRepository.java
- src/main/java/com/feelmycode/parabole/service/CartItemService.java
- src/main/java/com/feelmycode/parabole/service/CartService.java
- src/main/java/com/feelmycode/parabole/service/SellerService.java
장바구니 알고리즘 전체 수정
- DTO 추가
- 모호한 이름의 dto 수정
- 회원가입 로직에서 장바구니 생성부분 수정
#133
> [Feature/cart] 장바구니 알고리즘 수정

- src/main/java/com/feelmycode/parabole/controller/UserController.java
- src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/EventPrizeDto.java
- src/main/java/com/feelmycode/parabole/dto/UserInfoResponseDto.java
- src/main/java/com/feelmycode/parabole/repository/UserRepository.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
Feat: Coupon배정시 name으로 User검색 API 추가
쿠폰에서 user 조회시 필요한 API 추가
Feat: Seller Coupon List Dto 에 couponId 추가
이벤트 등록시 쿠폰 조회할때 필요해서 추가했어요
> [feature/coupon] Seller Coupon List Dto 에 couponId 추가, 쿠폰에서 user 조회시 필요한 API 추가

- src/main/java/com/feelmycode/parabole/controller/CouponController.java
- src/main/java/com/feelmycode/parabole/domain/Coupon.java
- src/main/java/com/feelmycode/parabole/dto/CouponAssignRequestDto.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
사용자에게 쿠폰을 배정해주는 API 
배정할 잔여 쿠폰 수량이 배정해 줄 사용자의 수보다 적으면 
쿠폰 배정이 불가하다고 메시지를 주는지 확인해주세요.
> [feature/coupon] 사용자에게 쿠폰을 배정해주는 API 

- src/main/java/com/feelmycode/parabole/controller/OrderController.java
- src/main/java/com/feelmycode/parabole/service/OrderService.java
> [feature/order] 코드 정리

- src/main/java/com/feelmycode/parabole/dto/OrderInfoSimpleDto.java
- src/main/java/com/feelmycode/parabole/dto/OrderUpdateRequestDto.java
- src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
- src/main/java/com/feelmycode/parabole/service/UpdateService.java
장바구니에서 값을 가져올 때 빈 값이 있는지 확인 및 FE에서 sellerId를 가져오는 부분을 지우고 Product에서 sellerId를 가져오도록 수정
> [feature/order] null값이 들어오는 것 처리 및 FE에서 넘기는 정보 수정을 위해 DTO의 변수 줄이기

- src/main/java/com/feelmycode/parabole/dto/OrderUpdateRequestDto.java
- src/main/java/com/feelmycode/parabole/service/UpdateService.java
주문 상태가 변경되었을 때 order state가 변하는 부분 BE에서 처리하도록 변경했습니다.
> [feature/order] 주문 상태가 변경되었을 때 order state가 변하는 부분 BE에서 처리하도록 변경

- src/main/java/com/feelmycode/parabole/controller/OrderController.java
- src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
- src/main/java/com/feelmycode/parabole/domain/Order.java
- src/main/java/com/feelmycode/parabole/repository/OrderRepository.java
- src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
- src/main/java/com/feelmycode/parabole/service/OrderService.java
- src/main/java/com/feelmycode/parabole/service/UpdateService.java
기존에 취소된 주문이 있는지 확인하는 부분을 수정했습니다. 
취소된 주문은 마이페이지에서 불러올 수 없도록 수정하겠습니다.
> [feature/order] 주문이 생성되는 로직 수정

- src/main/java/com/feelmycode/parabole/controller/EventController.java
- src/main/java/com/feelmycode/parabole/repository/EventRepository.java
- src/main/java/com/feelmycode/parabole/service/EventService.java
이벤트 목록 검색 파라미터를 RequestBody로 받는데 GetMapping을 사용해서 오류 발생
PostMapping으로 수정
> [feature/events] 이벤트 검색 조건 목록 조회 오류 수정

- src/main/java/com/feelmycode/parabole/dto/EventPrizeDto.java
> [feature/eventdetail] 이벤트상품 쿠폰 타입 추가

- src/main/java/com/feelmycode/parabole/dto/OrderBySellerDto.java
- src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
괄호가 잘못되어 있어 값이 안들어가는 문제와 
라인이 잘못되어있는 클래스 수정
> [feature/order] 상세 주문정보 못 가져오는 부분 수정

- src/main/java/com/feelmycode/parabole/controller/OrderController.java
- src/main/java/com/feelmycode/parabole/domain/Order.java
- src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
- src/main/java/com/feelmycode/parabole/dto/OrderDeliveryUpdateRequestDto.java
- src/main/java/com/feelmycode/parabole/dto/OrderInfoResponseDto.java
- src/main/java/com/feelmycode/parabole/dto/OrderRequestDto.java
- src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
- src/main/java/com/feelmycode/parabole/service/UpdateService.java
- src/test/java/com/feelmycode/parabole/controller/OrderControllerTest.java
재고와 썸네일을 가져올 수 있도록 코드 추가
productRemain과 productThumbnailImg의 값을 가져올 수 있도록 수정
> [feature/order] 재고와 썸네일 가져오는 코드 추가

- src/docs/asciidoc/snippets/update-order/curl-request.adoc
- src/docs/asciidoc/snippets/update-order/http-request.adoc
- src/docs/asciidoc/snippets/update-order/httpie-request.adoc
- src/docs/asciidoc/snippets/update-order/request-body.adoc
- src/docs/asciidoc/snippets/update-order/request-fields.adoc
- src/main/java/com/feelmycode/parabole/dto/OrderRequestDto.java
- src/main/java/com/feelmycode/parabole/service/UpdateService.java
- src/test/java/com/feelmycode/parabole/controller/OrderControllerTest.java
- userId로 name, email, phone을 가져올 수 있게 수정(입력받지않음)
- orderstate, orderinfostate BE에서 처리(입력받지않음)
입력받는 데이터를 줄임
BE에서 입력받지 않은 부분 처리
[#190]
> [feature/order] 주문 BE 수정

- src/main/java/com/feelmycode/parabole/controller/CouponController.java
쿠폰 목록 api 주석처리 왜 되어있는지 ㅠ 풀었습니다
> !HOTFIX: coupon list api 

- src/main/java/com/feelmycode/parabole/controller/AuthController.java
- src/main/java/com/feelmycode/parabole/domain/GoogleOauthToken.java
- src/main/java/com/feelmycode/parabole/domain/GoogleProfile.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
구글 로그인 구현
토큰과 회원 정보가 받아와 지는지 확인해주세요
카카오, 네이버 로그인
[#166 ]
> [feature/oauthgoogle] 구글 로그인 구현

- src/main/java/com/feelmycode/parabole/controller/AuthController.java
- src/main/java/com/feelmycode/parabole/domain/KakaoOauthToken.java
- src/main/java/com/feelmycode/parabole/domain/KakaoProfile.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
카카오 로그인 구현
토큰과 회원 정보가 받아와 지는지 확인해주세요
[#166 ]
> [feature/oauthkakao] 카카오 로그인 구현

- src/main/java/com/feelmycode/parabole/controller/UserController.java
- src/main/java/com/feelmycode/parabole/domain/Seller.java
- src/main/java/com/feelmycode/parabole/domain/User.java
- src/main/java/com/feelmycode/parabole/dto/UserToSellerDto.java
- src/main/java/com/feelmycode/parabole/service/UserService.java
Feat: 사용자를 판매자로 전환하는 API 구현
유저를 셀러로 변환하는 API 필요하시다는 팀원들 있어서 만들어 놨어요
애초에 seller 생성을 db에서 해주기로 했는데 api 로 동작하기 위해서는 seller 에 user가 @Notnull 이면 안되기 때문에 dev db 수정해놨고요, 코드도 그래서 바뀐거라고 미리 알려드려요
이렇게 하시라고 작성하는건 아니고요, 그냥 말씀 드립니다.
동작 확인하기 위해서 저는 dev branch 에서 유레카 관련 annotation 제거해야 동작하길래 그렇게 해서 확인했습니다.
> [feature/seller] 사용자를 판매자로 전환하는 API 구현

- src/main/java/com/feelmycode/parabole/controller/CouponController.java
- src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
- src/main/java/com/feelmycode/parabole/dto/CouponUseAndAssignRequestDto.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
BE api 에 로그인 헤더 적용했습니다.
아침에 말씀드린 API 에 @requestattribute 적용했습니다.
> [feature/couponjwt] 컨트롤러 header 로 받기

- src/main/java/com/feelmycode/parabole/service/UserService.java
> [feature/carthotfix] 회원가입 시에 장바구니 추가 

- src/main/java/com/feelmycode/parabole/controller/CouponController.java
> [feature/couponfix] Seller import 추가

- src/main/java/com/feelmycode/parabole/controller/CouponController.java
- 상품화면에서 상품-스토어의 쿠폰 리스트를 확인하기 위해 셀러ID를 파라미터로 받는 api가 필요해 @daeunchung 에게 요청함
> Feat: 필요한 API 추가

- src/main/java/com/feelmycode/parabole/dto/CouponUserResponseDto.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
Feat: 마이페이지-나의 쿠폰 목록에 반환값에 sellerId 추가
@jungeu1509 님 필요한 부분 해놨습니다.
> [feature/mypagecoupon] 마이페이지-나의 쿠폰 목록에 반환값에 sellerId 추가

- src/main/java/com/feelmycode/parabole/controller/ProductController.java
!HOTFIX: 판매자 상품 목록 api 변수 sellerId 로 수정
> [feature/hotfix-seller-product] 판매자 상품 목록 api 변수 sellerId 로 수정

- src/main/java/com/feelmycode/parabole/service/CouponService.java
- src/main/java/com/feelmycode/parabole/service/UpdateService.java
주문할 때 셀러별로 그룹화하여 쿠폰을 가져오는데 사용하지 않는 쿠폰을 가져오도록 수정
주문 상세 상태가 수정될 수 있도록 수정
> [feature/order_coupon] 주문할 때 사용할 수 있는 쿠폰만 가져오도록 수정, 주문 상세 상태 수정

- src/main/java/com/feelmycode/parabole/dto/CouponUseAndAssignRequestDto.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
- src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
Fix: 쿠폰 사용 안되는 부분 테스트
쿠폰 사용이 안된다고 하여 수정 후에 
모든 시나리오마다 실행시켜 보면서 테스트 후에 DB 확인했습니다
주문에서 쿠폰이 사용되는지 확인해주세요!
유효한 자신의 쿠폰 사용하기 전에 NotUsed인지 확인하고 사용API 찍고나서 Used 로 변경된 것을 확인했어요
> [fix/usecoupon] 쿠폰 사용 안되는 부분 수정 및 테스트

- src/main/java/com/feelmycode/parabole/controller/AwsS3Controller.java
판매자 상품 등록에서 이미지를 등록할 때 이미지가 중복되지 않도록 해결
> [feature/order] 상품등록 시 이미지가 중복저장되는 부분 해결

- script/run_dev.sh
- src/main/java/com/feelmycode/parabole/controller/AwsS3Controller.java
- src/main/java/com/feelmycode/parabole/controller/CouponController.java
- src/main/java/com/feelmycode/parabole/controller/ProductController.java
- src/main/java/com/feelmycode/parabole/dto/CouponUseAndAssignRequestDto.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
- src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
- src/main/java/com/feelmycode/parabole/service/UpdateService.java
- src/main/resources/application.yml
> [feature/dev tomain] 메인브랜치로 머지

- script/run_prod.sh
> Update run_prod.sh sh 파일 수정

- src/main/java/com/feelmycode/parabole/controller/AwsS3Controller.java
- src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
- src/main/java/com/feelmycode/parabole/controller/ProductController.java
- src/main/java/com/feelmycode/parabole/controller/UserController.java
- src/main/java/com/feelmycode/parabole/domain/Order.java
- src/main/java/com/feelmycode/parabole/service/CouponService.java
> [feature/order] 이미지 없음 처리와 todo삭제

- src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
- src/main/java/com/feelmycode/parabole/controller/ProductController.java
- src/main/java/com/feelmycode/parabole/service/ProductDetailService.java
상품/주문을 출력하는 개수 제한 추가 
상품 이미지가 없어도 출력되는 값이 있도록 수정
> [feature/order] 개수제한 추가 및 상품 이미지가 없어도 출력되는 값이 있도록 수정

- src/main/java/com/feelmycode/parabole/domain/Coupon.java
(제목은 작업한 내용을 간결하게 작성해주세요)
(작업중일 경우 제목 맨 앞에 [WIP]를 붙여주세요.)
(PR을 시작하게된 이유)
(어떤 부분 중점으로 봐달라, ~ 부분 잘 모르겠다, ~ 테스트 필요함 등)
(테스트 결과 첨부 혹은 리뷰어가 테스트할 수 있는 방법 제시)
(예시 : [#1][#2])
(괄호는 모두 지워주세요)
> Fix: 쿠폰 배정 수정
